# Generated by Django 2.0 on 2018-03-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdffile',
            name='file',
            field=models.FileField(upload_to='question_paper_files_pdf/'),
        ),
    ]
